### ISSUE TITLE
Add Edit command to Note functionality

### ISSUE THREAD

**Issue by cerulliulliulli** [r-DestinyTheGame/Sweeper-Bot#87]
`.note edit <user> <ID> <comment>` to allow for editing previously entered notes. Currently we have to `.note delete` and then `.note add` again.

**Comment by D0cR3d** [comment]
hey @Ex0dev this should be something pretty simple to do. Can you give this a try please?

**Comment by Ex0dev** [comment]
Sure, I'll get right on it ASAP

**Comment by D0cR3d** [comment]
Update: Edit command should be able to edit ANY note type, such as 'Note, Mute, Warn, Ban, Unban' which are the ActionTypes currently supported. This would allow us to edit any actions reason that we take.

The use case is that we initiate a warn to a use and use 'Please keep it civil' but want to have the database record be 'User said <specific bad word> aimed at <other user>' so that we don't have to repeat ALL details to the user.

this would mean we'd have to create another command specific for editing reasons, but it follows the same concept as editing notes.
